server:
  port: 8081

user-service:
  base-url: http://localhost:8080/api/v1/users

spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

jwt:
  secret-key: v3ryL0ngAndRand0mS3cr3tK3yThat1sH@rdToGu3ss123!4567890ABCDEFGHIJKL
  token-expiration-millis: 3600000 # 1 hour
  refresh-token-expiration-millis: 86400000 # 1 day