@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Пользователь" as u
participant "Фронт" as f
participant "Бэк" as b

u -> f
f -> b
b -->> f
f -->> u
alt case 1
  a -> b
else case 2
  a -> c
end
group
  a -> c
end
box Название
  participant "Название 1"
  participant "Название 2"
box end
Alice -> Bob: Authentication Request
activate Bob
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml